version: '3.8'
services:
  mysql-connessioni:
    container_name: mysqlConnessioni
    image: mysql:5.7
    volumes:
      - "$PWD/connessioni/mysql:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: connessioni
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mysql-ricette:
    container_name: mysqlRicette
    image: mysql:5.7
    volumes:
      - "$PWD/ricette/mysql:/docker-entrypoint-initdb.d"
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: ricette
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mysql-ricette-seguite:
    container_name: mysqlRicetteSeguite
    image: mysql:5.7
    volumes:
      - "$PWD/ricette-seguite/mysql:/docker-entrypoint-initdb.d"
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      #ricette-seguite creates problems with mysql
      MYSQL_DATABASE: ricette_seguite
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  consul:
    image: consul
    ports:
      - 8500:8500

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "connessioni:2:1,ricette:2:1"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  apigateway:
    container_name: apigateway
    build: ./api-gateway
    ports:
      - 8080:8080
    depends_on:
      - consul

  connessioni-service:
    #container_name: connessioni
    build: ./connessioni
    depends_on:
      - consul
      - mysql-connessioni
      - kafka
      - zookeeper

  ricette-service:
    #container_name: ricette
    build: ./ricette
    depends_on:
      - consul
      - mysql-ricette
      - kafka
      - zookeeper

  ricette-seguite-service:
    #container_name: ricette-seguite
    build: ./ricette-seguite
    depends_on:
      - consul
      - mysql-ricette-seguite
      - kafka
      - zookeeper
