version: '3.8'
services:
  mysql-connessioni:
    container_name: mysqlConnessioni
    image: mysql
    volumes:
      - "$PWD/mysql:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: connessioni

  mysql-ricette:
    container_name: mysqlRicette
    image: mysql
    volumes:
      - "$PWD/mysql:/docker-entrypoint-initdb.d"
    ports:
      - 3307:3306
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ricette

  mysql-ricette-seguite:
    container_name: mysqlRicetteSeguite
    image: mysql
    ports:
      - 3308:3306
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ricette-seguite

  consul:
    image: consul

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "connessioni-topic:2:1, ricette-topic:2:1"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  apigateway:
    build: ./api-gateway
    ports:
      - 8090:8080
    depends_on:
      - consul

  connessioni-service:
    build: ./connessioni
    depends_on:
      - consul
      - mysql-connessioni
      - kafka

  ricette-service:
    build: ./ricette
    depends_on:
      - consul
      - mysql-ricette
      - kafka

  ricette-seguite-service:
    build: ./ricette-seguite
    depends_on:
      - consul
      - mysql-ricette-seguite
      - kafka
