# application.yml
---
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          # spring.cloud.gateway.discovery.locator.enabled abilita la definizione implicita di rotte
          # sulla base dei servizi registrati nel servizio di service discover (default=false)
          # enabled: true
          enabled: false
      routes:
      - id: ricette_seguite_route
        uri: http://ricette-seguite.instagnam.svc.cluster.local:8080/ricetteseguite
        predicates:
        - Path=/ricetteseguite/**
      - id: ricette_route
        uri: http://ricette.instagnam.svc.cluster.local:8080/ricette
        predicates:
        - Path=/ricette/**
      - id: connessioni_route
        uri: http://connessioni.instagnam.svc.cluster.local:8080/connessioni
        predicates:
        - Path=/connessioni/**


server:
#  port: ${PORT:${SERVER_PORT:0}}
  port: 8080

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: info,health,gateway,beans

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.cloud.gateway: INFO
