# application.yml
--- 
spring: 
  application: 
    name: ricette
  kafka:
    bootstrap-servers: kafka-service:9092
    listener:
      missing-topics-fatal: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-ricette:3306/ricette
    username: user
    password: password
server:
  port: 8080


# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false

asw:
  kafka:
    channel:
      out: ricette


